---
title: "Introduction to andorR"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to andorR}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(andorR)

# Load the tree
tree<-load_tree_df(ethical)

# Ansewr some questions
set_answer(tree, "GOV5", TRUE, 3)
set_answer(tree, "ENV4", TRUE, 3)
set_answer(tree, "SOC1", TRUE, 3)

# Update the tree and view 
update_tree(tree)
print_tree(tree)

# Get the most important next questions
next_questions_df <- get_highest_influence(tree)
print(next_questions_df)

# Answer some more questions
set_answer(tree, "FIN4", TRUE, 3)
set_answer(tree, "FIN5", TRUE, 3)

# Update and view again
update_tree(tree)
print_tree(tree)

# Get the most important next questions
next_questions_df <- get_highest_influence(tree)
print(next_questions_df)

# Answer them
set_answer(tree, "GOV1", TRUE, 3)
set_answer(tree, "GOV2", TRUE, 3)
set_answer(tree, "GOV3", TRUE, 3)
set_answer(tree, "GOV4", TRUE, 3)
set_answer(tree, "FIN1", TRUE, 3)

# Update and get the final result
update_tree(tree)
print_tree(tree)
```
